# **Pandas**

# What is Pandas?
Pandas is a Python library used for data manipulation and analysis. It makes it easy to work with structured data such as CSV files, Excel sheets, SQL tables, and JSON data.

With Pandas, you can:
   1. Read CSV or Excel files
   2. Filter rows
   3. Select columns
   4. Calculate averages
   5. Handle missing values
   6. Sort data
   7. Group data
   8. Merge multiple datasets
   9. Prepare data for Machine Learning

# **Install Pandas**

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 324 kB/s eta 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /Users/vikky/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vikky/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 812 kB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 440 kB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

# **1. Series (1D)**

In [4]:
import pandas as pd

marks = pd.Series([80, 90, 95, 88])

print(marks)

0    80
1    90
2    95
3    88
dtype: int64

# **2. DataFrame (2D)**

In [16]:
import pandas as pd

data = {
    "Name": ["Vikky", "Rahul", "Aman"],
    "Age": [22, 21, 23],
    "Marks": [95, 88, 91]
}

df = pd.DataFrame(data)

In [17]:
df

    Name  Age  Marks
0  Vikky   22     95
1  Rahul   21     88
2   Aman   23     91

# **Reading Data**
CSV

In [4]:
df = pd.read_csv("Titanic-Dataset.csv")

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#check first five row 
df.head()

#check last five row 
#df.tail()

#check info
#df.info()

#Statistics 
#df.describe()

#check shape of the data
#df.shape

#check how may columns in data
#df.columns

#check type of the dataset
#df.dtypes

#check value counts 
#df.value_counts()

#check unique value in this dataset
#df.unique()

#short data
#df.sort_values()
#groupby

#df.groupby()

#df.merge()
#df.drop()
#df.fillna()
#df.isnull()

In [6]:
df.shape

(891, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# **Selecting Columns**
Single column

In [10]:
df["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

# **Selecting Rows**
Using position (iloc)

In [14]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [15]:
#first two rows
df.iloc[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
#Using labels
df.loc[0]

# **Filtering Data**
Students with marks greater than 90

In [18]:
df

    Name  Age  Marks
0  Vikky   22     95
1  Rahul   21     88
2   Aman   23     91

df[df["Marks"] > 90]

In [19]:
#Multiple conditions
df[(df["Marks"] > 90) & (df["Age"] > 21)]

    Name  Age  Marks
0  Vikky   22     95
2   Aman   23     91

# **Adding a Column**

df["Grade"] = ["A", "B", "A"]

# **Updating Values**

In [22]:
df.loc[2, "Marks"] = 99

# **Deleting Columns**

In [23]:
df

    Name  Age  Marks
0  Vikky   22     99
1  Rahul   21     88
2   Aman   23     99

In [ ]:
df.drop("Grade", axis=1)

# **Sorting**
Ascending

In [ ]:
df.sort_values("Marks")