In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
# read dataset using pandas 
data = pd.read_csv("Titanic-Dataset.csv")

In [ ]:
#check first five row in over dataset
data.head()

In [ ]:
#check last five row in over dataset
data.tail()

In [ ]:
#check shape over dataset
data.shape

In [ ]:
#check basic info over dataset
data.info()

In [ ]:
data.describe()

In [ ]:
data.describe(include="object")

In [ ]:
data.describe(include="all")

In [ ]:
data.corr()

In [ ]:
data.corr(numeric_only=True)

In [ ]:
data.columns

In [ ]:
data.duplicated().sum()

In [ ]:
data.iloc[0]

In [ ]:
data.head(11)

In [ ]:
data.iloc[10]

In [ ]:
data.iloc[10:21]

In [ ]:
#Specific rows and columns
data.iloc[0:5, 0:4]

In [ ]:
data['Age']

In [ ]:
#Select rows using condition
data.loc[data["Age"] > 50]

In [ ]:
data['Pclass'].value_counts()

In [ ]:
#Select specific columns
data.loc[data["Pclass"]==2, ["Name", "Age", "Sex","Cabin"]]

In [ ]:
data['Survived'].value_counts()

In [ ]:
#Passengers who survived
data.loc[data["Survived"] == 1]

In [ ]:
data.loc[data["Survived"] == 0]

In [ ]:
data['Survived'].value_counts()

In [ ]:
data['Sex'].value_counts()

In [ ]:
data.head(1)

In [ ]:
#Age greater than 50
data[data["Age"] > 50]

In [ ]:
data[data["Fare"] > 100]

In [ ]:
data["Pclass"].value_counts()

In [ ]:
#First-class passengers
data[data["Pclass"] == 1]

In [ ]:
#Female passengers
data[data["Sex"] == "female"]

In [ ]:
#Male passengers
data[data["Sex"] == "male"]

In [ ]:
#Age > 30 AND female
data[(data["Age"] > 30) & (data["Sex"] == "female") & (data['Pclass']==3)]

In [ ]:
data['Fare']

In [ ]:
#Age > 30 OR Fare > 100
data[(data["Age"] > 30) | (data["Fare"] > 100)]

In [ ]:
#Female AND survived
data[(data["Sex"] == "female") & (data["Survived"] == 1)]

In [ ]:
data[(data["Sex"] == "male") & (data["Survived"] == 0)]

In [ ]:
data['Embarked'].value_counts()

In [ ]:
#Find passengers from first or second class:
data[data["Pclass"].isin([1, 2])]

In [ ]:
data['Embarked']

In [ ]:
#Find passengers who embarked from C or S:
data[data["Embarked"].isin(["C", "S"])]

### query()

In [ ]:
data.query("Age > 50")

In [ ]:
data.query("Age > 30 and Fare > 50")

In [ ]:
data.isnull()

In [ ]:
data.isnull().sum()

In [ ]:
(data.isnull().sum() / len(data)) * 100

In [ ]:
data.notnull().sum()

In [ ]:
data.head()

In [ ]:
del data['PassengerId']

In [ ]:
#Remove Columns
data.drop("Cabin", axis=1)

In [ ]:
data.head()

In [ ]:
#Permanently remove:
data.drop("Cabin", axis=1, inplace=True)

In [ ]:
data.head()

In [ ]:
#Multiple columns:
data.drop(["Cabin", "Ticket"], axis=1, inplace=True)

In [ ]:
#Rename one column:
data.rename(columns={"Fare": "Ticket_Fare"}, inplace=True)

In [ ]:
data.head()

In [ ]:
#Rename Columns
data.rename(columns={
    "PassengerId": "Passenger_ID",
    "Survived": "Survival"
}, inplace=True)

In [ ]:
data.head(1)

In [ ]:
data['SibSp'].value_counts()

In [ ]:
data['Parch'].value_counts()

In [ ]:
#Add New Column
data["FamilySize"] = data["SibSp"] + data["Parch"] + 1

In [ ]:
data.head()

In [ ]:
data['FamilySize'].value_counts()

In [ ]:
data.info()

In [ ]:
data['Sex'].value_counts()

In [ ]:
data["Sex"] = data["Sex"].map({
    0: "male",
    1: "female"
})

In [ ]:
data.info()

In [ ]:
data['Survived'].value_counts()

In [ ]:
data["Sex"] = data["Sex"].map({
    "male": 0,
    "female": 1
})

In [ ]:
data.head()

In [ ]:
def age_group(age):
    if age < 18:
        return "Child"
    elif age < 60:
        return "Adult"
    else:
        return "Senior"

data["AgeGroup"] = data["Age"].apply(age_group)

In [ ]:
data["AgeGroup"] = data["Age"].apply(
    lambda x: "Child" if x < 18 else "Adult"
)

In [ ]:
#sort by age
data.sort_values("Age")

In [ ]:
data.sort_values("Age", ascending=False)

In [ ]:
data.sort_values(
    ["Pclass", "Fare"],
    ascending=[True, False]
)

In [ ]:
data["Sex"].unique()

In [ ]:
data["Sex"].value_counts()

In [ ]:
data["Survived"].value_counts(normalize=True) * 100

### Statistical Operations

In [ ]:
data["Age"].mean()

In [ ]:
data["Age"].median()

In [ ]:
data["Age"].mode()

In [ ]:
data["Age"].min()

In [ ]:
data["Age"].max()

In [ ]:
#Standard deviation
data["Age"].std()

In [ ]:
data["Age"].var()

In [ ]:
data["Fare"].sum()

###  GroupBy

In [ ]:
data.groupby("Sex")["Age"].mean()

In [ ]:
data.groupby("Pclass")["Fare"].median()

In [ ]:
data.groupby("Pclass")["Survived"].mean()

In [ ]:
data.groupby("Sex")["Survived"].mean()

In [ ]:
data.groupby("Pclass").agg({
    "Age": "mean",
    "Fare": "mean",
    "Survived": "sum"
})

## GroupBy Multiple Columns

In [ ]:
data.groupby(["Sex", "Pclass"])["Age"].mean()

In [ ]:
data.groupby(["Sex", "Pclass"]).agg({
    "Age": "mean",
    "Fare": "mean"
})

In [ ]:
#pivot_table()
pd.pivot_table(
    data,
    values="Survived",
    index="Sex",
    columns="Pclass",
    aggfunc="mean"
)

In [ ]:
data.head(1)

In [ ]:
pd.pivot_table(
    data,
    values="Age",
    index="Sex",
    columns="Pclass",
    aggfunc="count"
)

In [ ]:
#String Operations
data[data["Name"].str.contains("Mr")]

In [ ]:
data[data["Name"].str.contains("Mrs")]

In [ ]:
data["Title"] = data["Name"].str.extract(r",\s*([^.]*)\.")

In [ ]:
data.head()

In [ ]:
data['Title'].value_counts()

In [ ]:
data['Sex'].value_counts()

In [ ]:
data['Sex'] = data["Sex"].replace({
    "male": "M",
    "female": "F"
})

In [ ]:
data['Sex'].value_counts()

In [ ]:
data['Cabin'].value_counts(())

In [ ]:
data.head(10)

In [ ]:
data["Cabin"].replace(
    {None: "Unknown"}
)

In [ ]:
import numpy as np

data["SurvivalStatus"] = np.where(
    data["Survived"] == 1,
    "Survived",
    "Not Survived"
)

In [ ]:
data['SurvivalStatus'].value_counts()

In [ ]:
df2 = data.copy()

In [ ]:
df2.head()

In [ ]:
df1 = data[["PassengerId", "Name"]]
df2 = data[["PassengerId", "Survived"]]

result = pd.merge(
    df1,
    df2,
    on="PassengerId",
    how="inner"
)

pd.merge(df1, df2, how="inner")
pd.merge(df1, df2, how="left")
pd.merge(df1, df2, how="right")
pd.merge(df1, df2, how="outer")

In [32]:
result

     PassengerId                                               Name  Survived
0              1                            Braund, Mr. Owen Harris         0
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2              3                             Heikkinen, Miss. Laina         1
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
4              5                           Allen, Mr. William Henry         0
..           ...                                                ...       ...
886          887                              Montvila, Rev. Juozas         0
887          888                       Graham, Miss. Margaret Edith         1
888          889           Johnston, Miss. Catherine Helen "Carrie"         0
889          890                              Behr, Mr. Karl Howell         1
890          891                                Dooley, Mr. Patrick         0

[891 rows x 3 columns]

In [ ]:
df1.

   PassengerId                                               Name
0            1                            Braund, Mr. Owen Harris
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...
2            3                             Heikkinen, Miss. Laina
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4            5                           Allen, Mr. William Henry

In [28]:
df2.head()

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0

In [ ]:
pd.merge(df1, df2, how="inner")
pd.merge(df1, df2, how="left")
pd.merge(df1, df2, how="right")
pd.merge(df1, df2, how="outer")

In [33]:
data.to_csv("Titanic_Cleaned.csv", index=False)

In [36]:
data.to_excel("Titanic_Cleaned.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [35]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/openpyxl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/openpyxl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/openpyxl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/openpyxl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/openpyxl/
Could not fetch URL https://pypi.org/simple/openpyxl/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/openpyxl/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) - skipping
ERROR: Could not find a version that satisfies the requirement openpyxl (from versions: none)
ERROR: No matching distribution found for openpyxl
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.